inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Rakefile'
    - 'vendor/**/*'
    - 'spec/support/redis-client/**/*'

Naming/FileName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 140

RSpec/MultipleExpectations:
  Max: 3

Security/MarshalLoad:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
